### ISSUE TITLE
Errors in EclipseFP after update to scion-browser to 0.2.5

### ISSUE THREAD

**Issue by akaspin** [serras/scion-class-browser#18]
After updating I have some headache. EclipseFP tells me, what "Error update local database...". 

"Problem Occupied":

```
Error loading local database

Error loading local database
    unknown compression method
```

First Event in Error Log:

```
Error reading answer from Browser Server

java.util.zip.ZipException: unknown compression method
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at net.sf.eclipsefp.haskell.browser.client.StreamBrowserServer.getALine(StreamBrowserServer.java:160)
    at net.sf.eclipsefp.haskell.browser.client.StreamBrowserServer.sendAndReceiveOk(StreamBrowserServer.java:129)
    at net.sf.eclipsefp.haskell.browser.client.StreamBrowserServer.setCurrentDatabase(StreamBrowserServer.java:210)
    at net.sf.eclipsefp.haskell.browser.BrowserServer.loadLocalDatabase(BrowserServer.java:93)
    at net.sf.eclipsefp.haskell.browser.BrowserPlugin.loadLocalDatabase(BrowserPlugin.java:239)
    at net.sf.eclipsefp.haskell.ui.internal.scion.ScionManager$BrowserLocalDatabaseRebuildJob.run(ScionManager.java:1349)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Second Event in Error Log:

```
Error loading local database

java.util.zip.ZipException: unknown compression method
    at java.util.zip.InflaterInputStream.read(Unknown Source)
    at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at net.sf.eclipsefp.haskell.browser.client.StreamBrowserServer.getALine(StreamBrowserServer.java:160)
    at net.sf.eclipsefp.haskell.browser.client.StreamBrowserServer.sendAndReceiveOk(StreamBrowserServer.java:129)
    at net.sf.eclipsefp.haskell.browser.client.StreamBrowserServer.setCurrentDatabase(StreamBrowserServer.java:210)
    at net.sf.eclipsefp.haskell.browser.BrowserServer.loadLocalDatabase(BrowserServer.java:93)
    at net.sf.eclipsefp.haskell.browser.BrowserPlugin.loadLocalDatabase(BrowserPlugin.java:239)
    at net.sf.eclipsefp.haskell.ui.internal.scion.ScionManager$BrowserLocalDatabaseRebuildJob.run(ScionManager.java:1349)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

Shared scion-browser instance console:

```
>> {"filepath":"...workspace_path...\\.metadata\\.plugins\\net.sf.eclipsefp.haskell.browser\\scion-browser-0.2-dbs\\local.db","command":"load-local-db","rebuild":true}
"ok"
>> {"new-db":"_all","command":"set-current-db"}
```

**Comment by akaspin** [comment]
Ok. Problem appears exactly in version 0.2.5 of scion-browser because it add constraits to persistent\* >= 0.7. 

When I roll-back to persistent\* 0.6, all works good. I'm delete all from "AppData\cabal" and "AppData\ghc" and create following "world".

```
hoogle -any
buildwrapper -any
scion-browser == 0.2.3
hlint -any
persistent-template == 0.6.3.1
persistent-sqlite ==  0.6.2.1
```

But, I think - it's way to dark side.

So. Problem in persistent.

P.S. GHC 7.0.4

**Comment by JPMoresmau** [comment]
I don't have the problem with GHC 7.0.3 and persistent 0.7. Can you start scion-browser manually, then paste the two commands you have above (load-local-db and set-current-db), (just copy and paste the JSON in your console), and give the output?

**Comment by akaspin** [comment]
Log:

```
>scion-browser
{"filepath":"local.db","command":"load-local-db","rebuild":true}

... a lot of chatter ...
... really, really a lot of chatter...

[]
Local database loaded
x☺S╩╧Vт☻ ♥·☺)
```

... yes, exatly `x☺S╩╧Vт☻ ♥·☺)` with two smiles and heart, that's right. If I just press `Enter`... BANG

```
x☺S╩╧Vт☻ ♥·☺)
scion-browser: src\Main.hs:(35,15)-(44,93): Non-exhaustive patterns in case
```

... ok. Next try without `enter`

```
>scion-browser
{"filepath":"local.db","command":"load-local-db","rebuild":false}
Local database loaded
x☺S╩╧Vт☻ ♥·☺){"new-db":"_all","command":"set-current-db"}
error in command: mzero
```

Poor, poor me.

P.S. Windows 7 x64

**Comment by akaspin** [comment]
Ok. Now `scion-browser 0.2.3`, `persistent 0.6..`

```
 >scion-browser
 {"filepath":"local.db","command":"load-local-db","rebuild":true}

 ... a lot of chatter ...

 x☺S╩╧V☻ ☻╤☺▼
```

Err. Nevermind...

```
 x☺S╩╧V☻ ☻╤☺▼{"new-db":"_all","command":"set-current-db"}
```

All ok. No `error in command: mzero`

**Comment by JPMoresmau** [comment]
No, the weird symbols are normal, the data is compressed so it's normal. I understand what's happening: scion-browser's maintainer has released 2.0.5 without asking me first, which means that EclipseFP doesn't work any more with scion-browser. A command has been removed, set-current-db, so EclipseFP tries to run it and scion-browser fails. The short term solution is either to rollback to a previous version of scion-browser, as you did before, or to take the github version of EclipseFP. I'll try to release asap a new version of EclipseFP but since it comes with big changes in buildwrapper...

**Comment by akaspin** [comment]
Thank for explamation. So I'm not so hopeless.

**Comment by JPMoresmau** [comment]
Of course not, your investigations have been helpful to lead me to the source of the problem. I didn't realize at first that 0.2.5 was a new version...

**Comment by akaspin** [comment]
Thanks again
